// ---------- stick-figure pictures ----------
// Side-view cowgirl facing right. The poses (P) live in js/poses.js, generated by tools/poses.py from where the hands and feet go.
// Angles in degrees. t: torso, 0 = straight up, +90 = pointing right (forward). Limb angles: 0 = straight down, +90 = forward, 180 = up, -90 = back.
// ua/fa near arm (upper/fore), ua2/fa2 far arm; th/sh near leg (thigh/shin), th2/sh2 far leg.

// Furniture and props, drawn in the same 200 x 132 space (ground y=111). tether: a towel from that point to the near hand.
const PROPS={
 chairDip:{svg:'<path class="fill" d="M58 84h24v4H58z"/><path d="M60 88v23M80 88v23M58 88V58"/>'},
 chairBulg:{svg:'<path class="fill" d="M50 84h24v4H50z"/><path d="M52 88v23M72 88v23M50 88V58"/>'},
 chairFeet:{svg:'<path class="fill" d="M52 84h24v4H52z"/><path d="M54 88v23M74 88v23M52 88V58"/>'},
 chairCope:{svg:'<path class="fill" d="M48 84h24v4H48z"/><path d="M50 88v23M70 88v23M48 88V58"/>'},
 chairPistol:{svg:'<path class="fill" d="M58 84h24v4H58z"/><path d="M60 88v23M80 88v23M58 88V58"/>'},
 couchThrust:{svg:'<path class="fill" d="M6 86h60v25H6zM6 56h12v30H6z"/>'},
 couchStretch:{svg:'<path class="fill" d="M18 86h62v25H18zM18 56h12v30H18z"/>'},
 wallBack:{svg:'<path class="fill" d="M68-14h14v125H68z"/>'},
 wallBehind:{svg:'<path class="fill" d="M48-14h14v125H48z"/>'},
 wallFront:{svg:'<path class="fill" d="M168-14h14v125h-14z"/>'},
 doorframe:{svg:'<path class="fill" d="M146-14h8v125h-8z"/>'},
 door:{svg:'<path class="fill" d="M150-14h10v125h-10z"/><circle class="knob" cx="148" cy="58" r="2.5"/>',tether:[148,58]},
 table:{svg:'<path class="fill" d="M96 68h82v5H96z"/><path class="faint" d="M100 73v38M174 73v38"/>'},
 counter:{svg:'<path class="fill" d="M144 61h56v50h-56z"/><path d="M142 61h58"/>'},
 stepCalf:{svg:'<path class="fill" d="M70 101h42v10H70z"/>'},
 stepJeff:{svg:'<path class="fill" d="M64 101h44v10H64z"/>'},
 stairs:{svg:'<path class="fill" d="M120 101h22v10h-22zM142 91h22v20h-22zM164 81h30v30h-30z"/>'}
};

// Move name (any level) -> pose loop and optional prop. A level without its own entry uses the Build entry.
const F=(s,p)=>({s,p});
const FIG={
 // Burn
 "Step-back burpees":F(["stand","squatHands","plank","squatHands"]),
 "Burpees":F(["stand","squatHands","plank","pushDown","squatHands","jump"]),
 "Burpee tuck jumps":F(["stand","squatHands","plank","squatHands","tuck"]),
 "Squat pulses":F(["squat","squatHalf"]),
 "Jump squats":F(["squat","jump"]),
 "180° jump squats":F(["squat","jump"]),
 "Fast reverse lunges":F(["lungeUp","lunge"]),
 "Jumping lunges":F(["lunge","lungeAir","lungeSwitch","lungeAir"]),
 "Jumping lunge + knee drive":F(["lunge","kneeDriveHop"]),
 "Mountain climbers":F(["climb","climb2"]),
 "High knees":F(["highKnee","highKnee2"]),
 "Jumping jacks":F(["stand","jump"]),
 "Seal jacks + squat":F(["stand","jump","squat"]),
 "Step-out plank jacks":F(["plank","plankHop"]),
 "Plank jack + push-up":F(["plank","plankHop","pushDown"]),
 "Skaters":F(["skater","sideLand"]),
 "Squat thrusts":F(["stand","squatHands","plank","squatHands"]),
 "Sprawls":F(["stand","squatHands","sprawl","squatHands"]),
 "Sprawl + jump":F(["squatHands","sprawl","squatHands","jump"]),
 "Up-down planks on knees":F(["kneeForearm","kneeHandPlank"]),
 "Up-down planks":F(["forearmPlank","plank"]),
 "Up-down plank + jack":F(["forearmPlank","plank","plankHop"]),
 "Speed squats":F(["stand","squat"]),
 "Squat + calf raise jump":F(["squat","hop"]),
 "Squat jump + tuck":F(["squat","tuck"]),
 "Fast feet":F(["athletic","athletic2"]),
 "Fast feet + drop":F(["athletic","athletic2","prone"]),
 "Fast feet + sprawl":F(["athletic","athletic2","sprawl"]),
 // Strength
 "Knee push-ups":F(["kneePlank","kneePushDown"]),
 "Push-ups":F(["plank","pushDown"]),
 "Archer push-ups":F(["plank","pushDown"]),
 "Pike push-ups":F(["pike","pikeDown"]),
 "Feet-up pike push-ups":F(["pikeChair","pikeChairDown"],"chairFeet"),
 "Bent-knee chair dips":F(["dipUp","dipDown"],"chairDip"),
 "Straight-leg dips":F(["dipUpStraight","dipDownStraight"],"chairDip"),
 "Feet-up dips":F(["dipUpStraight","dipDownStraight"],"chairDip"),
 "Split squats":F(["splitUp","splitDown"]),
 "Bulgarian split squats":F(["bulgUp","bulgDown"],"chairBulg"),
 "Bulgarian + 2s pause":F(["bulgUp","bulgDown"],"chairBulg"),
 "Assisted pistols":F(["pistolDoorUp","pistolDoorDown"],"doorframe"),
 "Pistol to chair":F(["pistolUp","pistolChair"],"chairPistol"),
 "Pistol squats":F(["pistolUp","pistolDown"]),
 "Single-leg glute bridges":F(["slBridgeDown","slBridgeUp"]),
 "Single-leg hip thrusts":F(["thrustDown","thrustUp"],"couchThrust"),
 "Hip thrust + 3s hold":F(["thrustDown","thrustUp"],"couchThrust"),
 "Prone Y-raises":F(["prone","proneY"]),
 "Superman pull-downs":F(["proneY","proneW"]),
 "Table rows":F(["tableRowDown","tableRowUp"],"table"),
 "Towel door rows":F(["rowOut","rowIn"],"door"),
 "Prone reverse snow angels":F(["proneY","proneW"]),
 "Tuck-ups":F(["hollow","tuckUp"]),
 "V-ups":F(["hollow","vup"]),
 "Slow V-ups":F(["hollow","vup"]),
 "Downdog to cobra":F(["pike","cobra"]),
 "Hindu push-ups":F(["pike","swoop","cobra"]),
 "Dive-bomber push-ups":F(["pike","swoop","cobra"]),
 "Single-leg calf raises":F(["oneLeg","oneLegToe"]),
 "Single-leg on a step":F(["stepStand","stepToe"],"stepCalf"),
 "Step raise, 3s lower":F(["stepStand","stepToe"],"stepCalf"),
 "Tuck hollow hold":F(["hollowTuck"]),
 "Hollow body hold":F(["hollow"]),
 "Hollow rocks":F(["hollow","hollowRock"]),
 "Plank shoulder taps":F(["plank","plankTap"]),
 "Bear crawl":F(["bear","bear2"]),
 "Bear crawl + taps":F(["bear","bearTap"]),
 "Plank lean":F(["plank","plankLean"]),
 "Seated leg lifts":F(["sitTall","sitLift"]),
 "Tuck L-sit":F(["sitTall","tuckLsit"]),
 "L-sit":F(["sitTall","lsit"]),
 "Side plank":F(["sidePlank"]),
 "Side plank hip dips":F(["sidePlank","sidePlankDip"]),
 "Star side plank":F(["sidePlank","sidePlankStar"]),
 "Wall sit":F(["wallSit"],"wallBack"),
 "Wall sit, arms overhead":F(["wallSitUp"],"wallBack"),
 "Single-leg wall sit":F(["wallSitOne"],"wallBack"),
 // Athlete
 "Squat to calf raise":F(["squat","stand","tiptoe"]),
 "Broad jump, stick it":F(["squatLoad","broadFly","squatLand"]),
 "Broad jump + 180":F(["squatLoad","broadFly","squatLand"]),
 "Lateral step and stick":F(["skater","sideLand"]),
 "Pogo hops":F(["tiptoe","hop"]),
 "Tuck jumps":F(["stand","tuck"]),
 "Tuck jump + squat":F(["squat","tuck"]),
 "Single-leg deadlift (hold wall)":F(["stand","slDeadliftWall"],"wallFront"),
 "Single-leg deadlift":F(["stand","slDeadlift"]),
 "Single-leg deadlift + hop":F(["slDeadlift","slDeadliftHop"]),
 "Beast hold reaches":F(["beast","bearTap"]),
 "Beast kick-throughs":F(["beast","kickThrough"]),
 "Kick-through + crab reach":F(["beast","kickThrough"]),
 "Incline plyo push-ups":F(["inclineUp","inclineDown","inclineAir"],"counter"),
 "Plyo push-ups":F(["plank","pushDown","plankAir"]),
 "Clap push-ups":F(["plank","pushDown","plankAir"]),
 "Reverse lunge to knee drive":F(["lunge","kneeDrive"]),
 "Lunge, knee drive + hop":F(["lunge","kneeDriveHop"]),
 "Split jump to knee drive":F(["lunge","lungeAir","kneeDriveHop"]),
 "Sprint and drop":F(["highKnee","highKnee2","prone"]),
 "Sprint, drop, push-up":F(["highKnee","highKnee2","plank","pushDown"]),
 "Sprint, drop, burpee":F(["highKnee","highKnee2","squatHands","plank","jump"]),
 "Shuffle and touch":F(["athletic","athletic2","touchDown"]),
 "Shuffle, touch, jump":F(["athletic","touchDown","jump"]),
 "Shuffle + sprawl":F(["athletic","athletic2","sprawl"]),
 "Skater holds":F(["skater","sideLand"]),
 "Short Copenhagen plank":F(["copenhagen"],"chairCope"),
 "Copenhagen plank":F(["copenhagen"],"chairCope"),
 "Copenhagen + leg lifts":F(["copenhagen","copenhagenLift"],"chairCope"),
 // Mobility
 "Supported Cossack squats":F(["stand","cossack"]),
 "Deep squat hold (hold door)":F(["deepSquatDoor"],"doorframe"),
 "Deep squat pry":F(["deepSquat","deepSquatShift"]),
 "Deep squat, arms overhead":F(["deepSquatUp"]),
 "Standing roll-downs":F(["stand","rollDown"]),
 "Jefferson curl on a step":F(["stepStandTall","stepRollDown"],"stepJeff"),
 "Jefferson curl holding books":F(["stepStandTall","stepRollDown"],"stepJeff"),
 "Straddle reach":F(["sitTall","sitFold"]),
 "Bent-knee leg lifts":F(["sitTall","sitLift"]),
 "90/90 switches (hands back)":F(["seatedKnees","seated9090"]),
 "90/90 switches hands-free":F(["seatedKnees","seated9090Free"]),
 "90/90 to tall kneel":F(["seated9090","tallKneel"]),
 "World's greatest stretch":F(["lungeHand","wgs"]),
 "WGS + hamstring rock-back":F(["lungeHand","wgsRock"]),
 "WGS + hip lift":F(["lungeHand","wgs"]),
 "Half-kneeling hip flexor squeeze":F(["kneel","kneelLean"]),
 "Couch stretch":F(["couch"],"couchStretch"),
 "Couch stretch + hand lift":F(["couch","couchUp"],"couchStretch"),
 "Glute bridge hold":F(["backLie","bridgeUp"]),
 "Tabletop bridge":F(["seatedKnees","tabletop"]),
 "Full bridge":F(["backLie","wheel"]),
 "Prone Y-T raises":F(["prone","proneY","proneW"]),
 "Standing leg raises (hold wall)":F(["legRaiseLow","legRaise"],"wallBehind"),
 "Active leg raises":F(["stand","legRaise"]),
 "Leg raise + 3s hold":F(["stand","legRaise"]),
 "Frog rocks":F(["quad","frogBack"]),
 "Frog to deep squat":F(["frogBack","deepSquat"]),
 "Frogger jumps":F(["frogBack","jump"])
};
// wildcards, by name
const WILD_FIG=[
 [/stairs/i,["stepUp","stepUp2"],"stairs"],
 [/kitchen counter/i,["inclineUp","inclineDown","inclineAir"],"counter"],
 [/doorframe/i,["pistolDoorUp","pistolDoorDown"],"doorframe"],
 [/burpee|tabata|chorus|song/i,["stand","squatHands","plank","squatHands","jump"]],
 [/push-up/i,["plank","pushDown"]],
 [/jump squat|t-rex/i,["squat","jump"]],
 [/plank jack/i,["plank","plankHop"]],
 [/high knee|sprint|chase/i,["highKnee","highKnee2"]],
 [/hollow/i,["hollow"]],
 [/wall sit/i,["wallSitUp"],"wallBack"],
 [/deep squat/i,["deepSquat","deepSquatShift"]],
 [/lava|bound/i,["skater","sideLand"]],
 [/cossack/i,["stand","cossack"]],
 [/pistol/i,["pistolUp","pistolDown"]]
];

const FL={torso:34,neck:12,ua:18,fa:17,th:22,sh:22}, RAD=Math.PI/180;
function figPts(p){
  const g=a=>[Math.sin(a*RAD),Math.cos(a*RAD)];
  const H=[p.hx,p.hy], S=[H[0]+FL.torso*Math.sin(p.t*RAD),H[1]-FL.torso*Math.cos(p.t*RAD)];
  const Hd=[S[0]+FL.neck*Math.sin(p.t*RAD),S[1]-FL.neck*Math.cos(p.t*RAD)];
  const limb=(o,a1,a2,l1,l2)=>{const d1=g(a1),d2=g(a2),m=[o[0]+l1*d1[0],o[1]+l1*d1[1]];return [o,m,[m[0]+l2*d2[0],m[1]+l2*d2[1]]]};
  return {H,S,Hd,arm:limb(S,p.ua,p.fa,FL.ua,FL.fa),arm2:limb(S,p.ua2,p.fa2,FL.ua,FL.fa),leg:limb(H,p.th,p.sh,FL.th,FL.sh),leg2:limb(H,p.th2,p.sh2,FL.th,FL.sh)};
}
const KEYS=["hx","hy","t","ua","fa","ua2","fa2","th","sh","th2","sh2"];
const full=p=>{const o={};KEYS.forEach(k=>o[k]=p[k]??p[k.replace("2","")]);return o};
const POSE={}; Object.keys(P).forEach(k=>POSE[k]=full(P[k]));
const ptsStr=a=>a.map(q=>q[0].toFixed(1)+","+q[1].toFixed(1)).join(" ");
function figEntry(c){
  if(!c) return null;
  if(!c.wild) return FIG[c.n[c.lvl]]||FIG[c.n[0]]||null;
  for(const [re,s,p] of WILD_FIG) if(re.test(c.n)) return {s,p};
  return null;
}
function figFor(c){ const e=figEntry(c); return e?e.s:["stand","armsUp"]; }
function propFor(c){ const e=figEntry(c); return e&&e.p||""; }
let figProp="";
function drawPose(p){
  const q=figPts(p);
  $("body").setAttribute("points",ptsStr([q.H,q.S]));
  $("nearArm").setAttribute("points",ptsStr(q.arm)); $("farArm").setAttribute("points",ptsStr(q.arm2));
  $("nearLeg").setAttribute("points",ptsStr(q.leg)); $("farLeg").setAttribute("points",ptsStr(q.leg2));
  $("head").setAttribute("cx",q.Hd[0].toFixed(1)); $("head").setAttribute("cy",q.Hd[1].toFixed(1));
  const hd=`translate(${q.Hd[0].toFixed(1)},${q.Hd[1].toFixed(1)}) rotate(${p.t.toFixed(1)})`;
  $("hat").setAttribute("transform",hd); $("pony").setAttribute("transform",hd);
  const tt=PROPS[figProp]&&PROPS[figProp].tether, hand=q.arm[2];
  $("tether").setAttribute("points",tt?ptsStr([tt,hand]):"");
}
const reduceMotion=(()=>{try{return matchMedia("(prefers-reduced-motion: reduce)").matches}catch(e){return false}})();
let figSeq=["stand","armsUp"], figT0=0, figRAF=0;
function figFrame(now){
  if($("play").hidden||$("fig").hasAttribute("hidden")){ figRAF=0; return; }
  const SEG=1150, MOVE=850, n=figSeq.length, t=Math.max(0,now-figT0)/SEG;
  const i=Math.floor(t)%n, f=Math.min(1,((t%1)*SEG)/MOVE), e=.5-.5*Math.cos(Math.PI*f);
  const a=POSE[figSeq[i]], b=POSE[figSeq[(i+1)%n]], o={};
  KEYS.forEach(k=>o[k]=a[k]+(b[k]-a[k])*e);
  drawPose(o); figRAF=requestAnimationFrame(figFrame);
}
function setFig(seq,prop){
  figSeq=seq.filter(k=>POSE[k]); if(!figSeq.length) figSeq=["stand"];
  figProp=PROPS[prop]?prop:""; $("prop").innerHTML=figProp?PROPS[figProp].svg:"";
  $("fig").toggleAttribute("hidden",false);
  if(reduceMotion||figSeq.length<2){ drawPose(POSE[figSeq[Math.min(1,figSeq.length-1)]]); return; }
  figT0=performance.now(); if(!figRAF) figRAF=requestAnimationFrame(figFrame);
}

// Whole figure as SVG markup (debug/poses.html uses it to show every pose at once).
const HAT_D="M-6.5-5.5C-7.5-13-4-15-1.5-13.3 0-12.3 0-12.3 1.5-13.3 4-15 7.5-13 6.5-5.5ZM-13.5-6C-11-2.5 11-2.5 13.5-6 11-4.4-11-4.4-13.5-6Z";
function figSVG(p,prop){
  const q=figPts(p), hd=`translate(${q.Hd[0].toFixed(1)},${q.Hd[1].toFixed(1)}) rotate(${p.t.toFixed(1)})`, pr=PROPS[prop];
  return `<line class="ground" x1="10" y1="111" x2="190" y2="111"></line><g class="prop">${pr?pr.svg:""}</g>`+
    (pr&&pr.tether?`<polyline class="tether" points="${ptsStr([pr.tether,q.arm[2]])}"></polyline>`:"")+
    `<g class="far"><polyline points="${ptsStr(q.arm2)}"></polyline><polyline points="${ptsStr(q.leg2)}"></polyline></g>`+
    `<g class="near"><polyline points="${ptsStr([q.H,q.S])}"></polyline><polyline points="${ptsStr(q.arm)}"></polyline><polyline points="${ptsStr(q.leg)}"></polyline>`+
    `<path class="pony" d="M-5-4C-13-3-15 3-12 10" transform="${hd}"></path><circle cx="${q.Hd[0].toFixed(1)}" cy="${q.Hd[1].toFixed(1)}" r="7.5"></circle><path class="hat" d="${HAT_D}" transform="${hd}"></path></g>`;
}
